--------------------------------------------------------
--  Constraints for Table TBLADMIN
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLADMIN" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLADMIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLMAKEUPCLASSINFO
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLMAKEUPCLASSINFO" ADD PRIMARY KEY ("SCOREBYSUBJECTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLSUBJECTBYCOURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSUBJECTBYCOURSE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSUBJECTBYCOURSE" MODIFY ("SUBJECTNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSUBJECTBYCOURSE" MODIFY ("ALLCOURSENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLOPENCOURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLOPENCOURSE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLOPENCOURSE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLOPENCOURSE" MODIFY ("ALLCOURSENUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLOPENCOURSE" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLOPENCOURSE" MODIFY ("STARTDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSTUDENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSTUDENT" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSTUDENT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSTUDENT" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSTUDENT" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSTUDENT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSUPPORTLIST
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSUPPORTLIST" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSUPPORTLIST" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLCOURSEHISTORY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLCOURSEHISTORY" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLCOURSEHISTORY" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLCOURSEHISTORY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLCOURSEHISTORY" MODIFY ("OPENCOURSENUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLCOURSEHISTORY" MODIFY ("STUDENTNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLEQUIPMENTBYCLASSROOM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLEQUIPMENTBYCLASSROOM" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLEQUIPMENTBYCLASSROOM" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLEQUIPMENTBYCLASSROOM" MODIFY ("EQUIPMENTNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLEQUIPMENTBYCLASSROOM" MODIFY ("CLASSROOMNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLPERIODBYSUBJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLPERIODBYSUBJECT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLPERIODBYSUBJECT" MODIFY ("SUBJECTBYCOURSENUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLPERIODBYSUBJECT" MODIFY ("OPENCOURSENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLDISTRIBUTION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLDISTRIBUTION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLDISTRIBUTION" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLDISTRIBUTION" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLDISTRIBUTION" MODIFY ("BOOKNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLTEACHER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLTEACHER" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLTEACHER" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLTEACHER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLTEACHER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLBOOK
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLBOOK" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLBOOK" MODIFY ("SUBJECTNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLEQUIPMENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLEQUIPMENT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLEQUIPMENT" MODIFY ("ITEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSUPPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSUPPORT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSUPPORT" MODIFY ("SUPPORTLISTNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSUPPORT" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLRATING
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLRATING" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLRATING" MODIFY ("RATINGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLRATING" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLALLCOURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLALLCOURSE" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLALLCOURSE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLALLCOURSE" MODIFY ("PERIOD" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLALLCOURSE" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLALLCOURSE" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLALLCOURSE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLATTENDANCE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLATTENDANCE" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLATTENDANCE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLATTENDANCE" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLQUESTIONBYEXAM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLQUESTIONBYEXAM" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLQUESTIONBYEXAM" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLQUESTIONBYEXAM" MODIFY ("EXAMNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLCONSULTREQUEST
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLCONSULTREQUEST" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLCONSULTREQUEST" MODIFY ("REQUSETDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLCONSULTREQUEST" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSCOREBYRATING
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSCOREBYRATING" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSCOREBYRATING" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSCOREBYRATING" MODIFY ("RATINGQUESTIONNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSCOREBYRATING" MODIFY ("RATINGNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSUBJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSUBJECT" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSUBJECT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSUBJECT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLAVAILABLESUBJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLAVAILABLESUBJECT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLAVAILABLESUBJECT" MODIFY ("SUBJECTNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLAVAILABLESUBJECT" MODIFY ("TEACHERNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLEXAM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLEXAM" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLEXAM" MODIFY ("SUBJECTBYCOURSENUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLEXAM" MODIFY ("OPENCOURSENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLRATINGQUESTION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLRATINGQUESTION" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLRATINGQUESTION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLHIREDGRADUATES
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLHIREDGRADUATES" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLHIREDGRADUATES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLHIREDGRADUATES" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLSCOREBYSUBJECT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLSCOREBYSUBJECT" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLSCOREBYSUBJECT" MODIFY ("EXAMNUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLSCOREBYSUBJECT" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLJOBACTIVITY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLJOBACTIVITY" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLJOBACTIVITY" MODIFY ("COURSEHISTORYNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLCLASSROOM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLCLASSROOM" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLCLASSROOM" MODIFY ("CAPACITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBLOUTSTANDINGREWARD
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLOUTSTANDINGREWARD" ADD PRIMARY KEY ("SCOREBYSUBJECTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLCONSULTLOG
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TBLCONSULTLOG" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."TBLCONSULTLOG" MODIFY ("CONSULTDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TBLCONSULTLOG" MODIFY ("CONSULTREQUESTNUM" NOT NULL ENABLE);
