--------------------------------------------------------
--  DDL for Table TBLADMIN
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLADMIN" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLALLCOURSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLALLCOURSE" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(150 BYTE), 
	"PURPOSE" VARCHAR2(300 BYTE), 
	"CAPACITY" NUMBER, 
	"PERIOD" NUMBER, 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLATTENDANCE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLATTENDANCE" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"ENTERTIME" DATE, 
	"OUTTIME" DATE, 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLAVAILABLESUBJECT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLAVAILABLESUBJECT" 
   (	"NUM" NUMBER, 
	"TEACHERNUM" NUMBER, 
	"SUBJECTNUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLBOOK
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLBOOK" 
   (	"NUM" NUMBER, 
	"SUBJECTNUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"WRITER" VARCHAR2(30 BYTE), 
	"PUBLISHER" VARCHAR2(30 BYTE), 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLCLASSROOM
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLCLASSROOM" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"CAPACITY" NUMBER, 
	"DELETESTATUS" VARCHAR2(5 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLCONSULTLOG
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLCONSULTLOG" 
   (	"NUM" NUMBER, 
	"CONSULTREQUESTNUM" NUMBER, 
	"CONSULTDATE" DATE, 
	"CONSULTCONTENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLCONSULTREQUEST
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLCONSULTREQUEST" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"REQUSETDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLCOURSEHISTORY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLCOURSEHISTORY" 
   (	"NUM" NUMBER, 
	"STUDENTNUM" NUMBER, 
	"OPENCOURSENUM" NUMBER, 
	"STATUS" VARCHAR2(15 BYTE), 
	"ENDDATE" DATE, 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLDISTRIBUTION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLDISTRIBUTION" 
   (	"NUM" NUMBER, 
	"BOOKNUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"STATUS" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PROJECT"."TBLDISTRIBUTION"."STATUS" IS '1: yes, 0: not';
--------------------------------------------------------
--  DDL for Table TBLEQUIPMENT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLEQUIPMENT" 
   (	"NUM" NUMBER, 
	"ITEM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLEQUIPMENTBYCLASSROOM
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLEQUIPMENTBYCLASSROOM" 
   (	"NUM" NUMBER, 
	"CLASSROOMNUM" NUMBER, 
	"EQUIPMENTNUM" NUMBER, 
	"QTY" NUMBER, 
	"BUYINGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLEXAM
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLEXAM" 
   (	"NUM" NUMBER, 
	"OPENCOURSENUM" NUMBER, 
	"SUBJECTBYCOURSENUM" NUMBER, 
	"TESTDATE" DATE, 
	"WRITTENTESTRATIO" NUMBER, 
	"PERFORMANCETESTRATIO" NUMBER, 
	"ATTENDANCERATIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLHIREDGRADUATES
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLHIREDGRADUATES" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"COMPANY" VARCHAR2(30 BYTE), 
	"SALARY" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLJOBACTIVITY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLJOBACTIVITY" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"CONTENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLMAKEUPCLASSINFO
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLMAKEUPCLASSINFO" 
   (	"SCOREBYSUBJECTNUM" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLOPENCOURSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLOPENCOURSE" 
   (	"NUM" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"CLASSROOMNUM" NUMBER, 
	"TEACHERNUM" NUMBER, 
	"ALLCOURSENUM" NUMBER, 
	"STATUS" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLOUTSTANDINGREWARD
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLOUTSTANDINGREWARD" 
   (	"SCOREBYSUBJECTNUM" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLPERIODBYSUBJECT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLPERIODBYSUBJECT" 
   (	"NUM" NUMBER, 
	"OPENCOURSENUM" NUMBER, 
	"SUBJECTBYCOURSENUM" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLQUESTIONBYEXAM
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLQUESTIONBYEXAM" 
   (	"NUM" NUMBER, 
	"EXAMNUM" NUMBER, 
	"TYPE" VARCHAR2(10 BYTE), 
	"QUESTION" VARCHAR2(300 BYTE), 
	"ANSWER" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLRATING
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLRATING" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"RATINGDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLRATINGQUESTION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLRATINGQUESTION" 
   (	"NUM" NUMBER, 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSCOREBYRATING
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSCOREBYRATING" 
   (	"NUM" NUMBER, 
	"RATINGNUM" NUMBER, 
	"RATINGQUESTIONNUM" NUMBER, 
	"SCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSCOREBYSUBJECT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSCOREBYSUBJECT" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"EXAMNUM" NUMBER, 
	"WRITTENTESTSCORE" NUMBER, 
	"PERFORMANCETESTSCORE" NUMBER, 
	"ATTENDANCESCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSTUDENT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSTUDENT" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"SSN" VARCHAR2(15 BYTE), 
	"REGISTERDATE" DATE DEFAULT sysdate /* 최초 등록일 */, 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSUBJECT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSUBJECT" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"ESSENTIALTYPE" VARCHAR2(10 BYTE), 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSUBJECTBYCOURSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSUBJECTBYCOURSE" 
   (	"NUM" NUMBER, 
	"ALLCOURSENUM" NUMBER, 
	"SUBJECTNUM" NUMBER, 
	"SEQ" NUMBER, 
	"PERIOD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSUPPORT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSUPPORT" 
   (	"NUM" NUMBER, 
	"COURSEHISTORYNUM" NUMBER, 
	"SUPPORTLISTNUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSUPPORTLIST
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLSUPPORTLIST" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTEACHER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TBLTEACHER" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"SSN" VARCHAR2(15 BYTE), 
	"DELETESTATUS" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
